@startuml DGW Object PUT

header DGW Object PUT \n By Zuhair AlSader\n2022-01-31
title DGW Object PUT

participant "RGWPutObj" as rgw
participant "DaosStore" as store
participant "DaosAtomicWriter" as writer
participant "DaosObject" as object
participant "LibDS3" as libds3
participant "LibDFS" as libdfs

autoactivate on

rgw -> store: get_atomic_writer()
store --> rgw: new DaosAtomicWriter


rgw -> writer: prepare()
writer -> object: open(key)
object -> libds3: ds3_obj_create(key)

loop dir_name in split(key, /)
  libds3 -> libdfs: dfs_mkdir(dir_name)
  libdfs --> libds3: success or exists
end

libds3 -> libdfs: dfs_open(file_name, O_CREAT)
libdfs --> libds3: return DFS object handle

libds3 --> object: return DS3 object handle
object --> writer: success
writer --> rgw: success

loop over data sections
  rgw -> writer: process(data, offset)
  writer -> libds3: ds3_obj_write(data, offset)
  libds3 -> libdfs: dfs_write(data, offset)
  libdfs --> libds3: success
  libds3 --> writer: success
  writer --> rgw: success
end

writer -> object: <<destroy>>
object -> libds3: ds3_obj_destroy()
libds3 -> libdfs: dfs_release()
libdfs --> libds3: success
libds3 --> object: success
destroy object

@enduml